// Generated by CoffeeScript 2.7.0
(function() {
  var Url, drawTiles, endGame, endTurn, getUrlVars, handleGameOver, handleMoveResult, handleOpponentQuit, handleTick, handleTimeIsUp, handleWelcome, handleYourTurnNow, iceHTMLChar, myNum, myTurn, root, selectedCoordinates, showMessage, showMoveResult, showNotice, socket, startGame, startTurn, swapTiles, tileClick, tiles, toArray, turnColor, turnColorGreen, turnColorRed, turnColorYellow, turnTime, typeAndContent, updateUsedWords, usedWords;

  socket = tiles = selectedCoordinates = myNum = myTurn = usedWords = turnTime = null;

  turnColorGreen = "#181";

  turnColorRed = "#d32";

  turnColorYellow = "#FFFFB6";

  turnColor = turnColorGreen;

  Url = {
    encode: function(string) {
      return escape(this._utf8_encode(string));
    },
    decode: function(string) {
      return this._utf8_decode(unescape(string));
    },
    _utf8_encode: function(string) {
      var c, n, utftext;
      string = string.replace(/\r\n/g, "\n");
      utftext = "";
      n = 0;
      while (n < string.length) {
        c = string.charCodeAt(n);
        if (c < 128) {
          utftext += String.fromCharCode(c);
        } else if ((c > 127) && (c < 2048)) {
          utftext += String.fromCharCode((c >> 6) | 192);
          utftext += String.fromCharCode((c & 63) | 128);
        } else {
          utftext += String.fromCharCode((c >> 12) | 224);
          utftext += String.fromCharCode(((c >> 6) & 63) | 128);
          utftext += String.fromCharCode((c & 63) | 128);
        }
        n++;
      }
      return utftext;
    },
    _utf8_decode: function(utftext) {
      var c, c1, c2, c3, i, string;
      string = "";
      i = 0;
      c = c1 = c2 = 0;
      while (i < utftext.length) {
        c = utftext.charCodeAt(i);
        if (c < 128) {
          string += String.fromCharCode(c);
          i++;
        } else if ((c > 191) && (c < 224)) {
          c2 = utftext.charCodeAt(i + 1);
          string += String.fromCharCode(((c & 31) << 6) | (c2 & 63));
          i += 2;
        } else {
          c2 = utftext.charCodeAt(i + 1);
          c3 = utftext.charCodeAt(i + 2);
          string += String.fromCharCode(((c & 15) << 12) | ((c2 & 63) << 6) | (c3 & 63));
          i += 3;
        }
      }
      return string;
    }
  };

  iceHTMLChar = function(c) {
    switch (c) {
      case 'Á':
        return '&Aacute;';
      case 'Ð':
        return '&ETH;';
      case 'É':
        return '&Eacute;';
      case 'Í':
        return '&Iacute;';
      case 'Ó':
        return '&Oacute;';
      case 'Ú':
        return '&Uacute;';
      case 'Ý':
        return '&Yacute;';
      case 'Þ':
        return '&THORN;';
      case 'Æ':
        return '&AElig;';
      case 'Ö':
        return '&Ouml;';
      case 'á':
        return '&#225;';
      case 'ð':
        return '&#240;';
      case 'é':
        return '&#233;';
      case 'í':
        return '&#237;';
      case 'ó':
        return '&#243;';
      case 'ý':
        return '&#253;';
      case 'þ':
        return '&#254;';
      case 'æ':
        return '&#230;';
      case 'ö':
        return '&#246;';
      default:
        return c;
    }
  };

  getUrlVars = function() {
    var parts, vars;
    vars = {};
    parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/g, function(m, key, value) {
      return vars[key] = value;
    });
    return vars;
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.iceHTMLChar = iceHTMLChar;

  root.Url = Url;

  root.getUrlVars = getUrlVars;

  // forced = true when last turn ended because a player took too long
  startTurn = function(player, forced = false) {
    myTurn = true;
    $('#grid').removeClass('turnColorRed turnColorYellow').addClass('turnColorGreen');
    $('#opponentTimer').hide();
    $('#meTimer').show();
    if (forced) {
      $("#opponentTimer").html("0");
      showMoveResult(player, null, 0, []);
      return showMessage('yourTurnNow');
    } else {
      return showMessage('firstTile');
    }
  };

  endTurn = function(player, forced = false) {
    selectedCoordinates = null;
    myTurn = false;
    $('#grid').removeClass('turnColorGreen turnColorYellow').addClass('turnColorRed');
    $('#meTimer').hide();
    $('#opponentTimer').show();
    if (forced) {
      $('#meTimer').html("0");
      showMoveResult(player, null, 0, []);
      return showMessage('timeIsUp');
    } else {
      return showMessage('waitForMove');
    }
  };

  drawTiles = function(x1, y1, x2, y2) {
    var gridHtml, j, k, ref, ref1, x, y;
    gridHtml = '';
    for (x = j = 0, ref = tiles.length; (0 <= ref ? j < ref : j > ref); x = 0 <= ref ? ++j : --j) {
      gridHtml += '<ul>';
      for (y = k = 0, ref1 = tiles.length; (0 <= ref1 ? k < ref1 : k > ref1); y = 0 <= ref1 ? ++k : --k) {
        gridHtml += `<li id='tile${x}_${y}'>${iceHTMLChar(tiles[x][y])}</li>`;
      }
      gridHtml += '</ul>';
    }
    // draw the grid and highlight the recently swapped tiles
    return $('#grid').html(gridHtml).find(`li#tile${x1}_${y1}`).add(`li#tile${x2}_${y2}`).effect("highlight", {
      color: turnColor
    }, 3000);
  };

  showMessage = function(messageType) {
    var effectColor, messageHtml;
    effectColor = "#FFF";
    switch (messageType) {
      case 'waitForConnection':
        messageHtml = "Bíð eftir mótspilara";
        $('#usedwords, #grid, #opponentScore, #meScore').hide();
        break;
      case 'waitForMove':
        messageHtml = "Mótspilarinn á leik";
        break;
      case 'firstTile':
        messageHtml = "Veldu fyrri stafinn";
        effectColor = turnColorGreen;
        break;
      case 'secondTile':
        messageHtml = "Veldu seinni stafinn";
        effectColor = turnColorGreen;
        break;
      case 'timeIsUp':
        messageHtml = "Þú féllst á tíma";
        effectColor = turnColorRed;
        break;
      case 'yourTurnNow':
        messageHtml = "Mótspilarinn féll á tíma";
        effectColor = turnColorGreen;
        break;
      case 'opponentQuit':
        messageHtml = "Mótspilarinn hætti";
        $('#usedwords, #grid').hide();
        break;
      case 'gameOver':
        messageHtml = "";
        $('#usedwords, #meTimer, #opponentTimer').hide();
    }
    $('#message').html(messageHtml);
    return $('#message').effect("highlight", {
      color: `${effectColor}`
    }, 5500);
  };

  tileClick = function() {
    var $this, x, y;
    if (!myTurn) {
      return;
    }
    $this = $(this);
    if ($this.hasClass('selected')) {
      // undo
      selectedCoordinates = null;
      $this.removeClass('selected');
      return showMessage('firstTile');
    } else {
      [x, y] = this.id.match(/(\d+)_(\d+)/).slice(1);
      if (selectedCoordinates === null) {
        selectedCoordinates = {
          x1: x,
          y1: y
        };
        $this.addClass('selected');
        return showMessage('secondTile');
      } else {
        selectedCoordinates.x2 = x;
        selectedCoordinates.y2 = y;
        socket.emit("move", JSON.stringify(selectedCoordinates));
        return endTurn(null, false);
      }
    }
  };

  swapTiles = function({x1, y1, x2, y2}) {
    [tiles[x1][y1], tiles[x2][y2]] = [tiles[x2][y2], tiles[x1][y1]];
    return drawTiles(x1, y1, x2, y2);
  };

  updateUsedWords = function(newWords) {
    var allUsedWords, newWordsHtmlSorted;
    // if no usedwords, initialize with new words
    if (Object.keys(usedWords).length === 0) {
      newWordsHtmlSorted = newWords.wordsHtml.split(", ").sort(function(a, b) {
        return a.localeCompare(b);
      }).join(", ");
      [usedWords.wordsHtml, usedWords.defs] = [newWordsHtmlSorted, newWords.defs];
    // otherwise only update usedWords if there are newWords formed during move
    } else if (newWords.wordsHtml.length > 0) {
      allUsedWords = usedWords.wordsHtml.concat(", " + newWords.wordsHtml);
      usedWords.wordsHtml = allUsedWords.split(", ").sort().join(", ");
      usedWords.wordsHtml = allUsedWords.split(", ").sort(function(a, b) {
        return a.localeCompare(b);
      }).join(", ");
    }
    return $('#usedwords').html(usedWords.wordsHtml);
  };

  handleWelcome = function(data) {
    var currPlayerNum, newWords, players;
    ({
      players,
      currPlayerNum,
      tiles,
      yourNum: myNum,
      newWords,
      turnTime
    } = JSON.parse(data));
    startGame(players, currPlayerNum);
    $('#usedwords, #grid, #meScore, #opponentScore').show();
    $('#usedwords').html("");
    usedWords = {};
    return updateUsedWords(newWords);
  };

  handleMoveResult = function(data) {
    var moveScore, newWords, player, swapCoordinates;
    ({player, swapCoordinates, moveScore, newWords} = JSON.parse(data));
    showMoveResult(player, swapCoordinates, moveScore, newWords);
    return updateUsedWords(newWords);
  };

  handleOpponentQuit = function() {
    return showMessage('opponentQuit');
  };

  handleTimeIsUp = function(data) {
    var player;
    player = JSON.parse(data);
    return endTurn(player, true);
  };

  handleYourTurnNow = function(data) {
    var player;
    player = JSON.parse(data);
    return startTurn(player, true);
  };

  handleTick = function(data) {
    var nonTurnTimer, tick, turnTimer;
    // tick for first tick of turn, tock for others
    tick = JSON.parse(data);
    if (myTurn) {
      turnTimer = "#meTimer";
      nonTurnTimer = "#opponentTimer";
    } else {
      turnTimer = "#opponentTimer";
      nonTurnTimer = "#meTimer";
    }
    if (tick === "tick") {
      $(turnTimer).html(turnTime);
      $(nonTurnTimer).hide();
      return $(turnTimer).show();
    } else {
      $(turnTimer).html(parseInt($(turnTimer).html()) - 1);
      if (parseInt($(turnTimer).html()) <= 5) {
        return $(turnTimer).removeClass('turnColorRed turnColorGreen').addClass('turnColorYellow');
      }
    }
  };

  handleGameOver = function(data) {
    var winner;
    ({
      winner,
      yourNum: myNum
    } = JSON.parse(data));
    return endGame(winner);
  };

  typeAndContent = function(message) {
    var content, ignore, type;
    [ignore, type, content] = message.match(/(.*?):(.*)/);
    return {type, content};
  };

  toArray = function(newWords) {
    var key, ref, value, words;
    words = [];
    ref = newWords.defs;
    for (key in ref) {
      value = ref[key];
      words.push(key);
    }
    return words;
  };

  showNotice = function(moveScore, newWords, player) {
    var $notice, fannOrdTexti, messageLocation, words;
    words = toArray(newWords);
    $notice = $("<p class='notice'></p>");
    if (moveScore === 0) {
      if (player.num === myNum) {
        return $notice.html("Þú fannst engin ný orð");
      } else {
        return $notice.html(`${player.name} fann engin ný orð`);
      }
    } else {
      fannOrdTexti = `${player.name} fann `;
      messageLocation = '#opponentMoveList';
      if (player.num === myNum) {
        fannOrdTexti = "Þú fannst ";
        messageLocation = '#meMoveList';
      }
      $notice.html(`${fannOrdTexti} ${words.length} orð:<br /> 
<b>${words.join(', ')}</b><br /> 
sem gefur <b>${moveScore / words.length}x${words.length}
= ${moveScore}</b> stig!`);
      $notice.insertAfter($(messageLocation));
      return $notice.effect("highlight", {
        color: "#eb4"
      }, 7500, function() {
        return $notice.remove();
      });
    }
  };

  startGame = function(players, currPlayerNum) {
    $("#meName").html(players[myNum - 1].name);
    $("#meScore").html(players[myNum - 1].score);
    $("#opponentName").html(players[2 - myNum].name);
    $("#opponentScore").html(players[2 - myNum].score);
    drawTiles();
    if (myNum === currPlayerNum) {
      return startTurn(players[2 - myNum], false);
    } else {
      return endTurn(players[myNum - 1], false);
    }
  };

  endGame = function(winner) {
    $("#grid").html(`<center>
<p>&nbsp;</p>
<p>&nbsp;</p>
Leik lokið!
<p>&nbsp;</p>
<p>&nbsp;</p>
${winner.name} vann!
<p>&nbsp;</p>
<p>&nbsp;</p>
<FORM>
<INPUT type="button" value="Nýr leikur" onClick="history.go(-1);return true;">
</FORM>
</center>`);
    return showMessage('gameOver');
  };

  showMoveResult = function(player, swapCoordinates, moveScore, newWords) {
    var moveString, words;
    words = toArray(newWords);
    moveString = `<b>${player.moveCount}: 0</b><br/>`;
    if (words.length > 0) {
      moveString = `<b>${player.moveCount}: ${moveScore}</b> - ${words.join(', ')}<br/>`;
    }
    console.log(player);
    if (player.num === myNum) {
      $("#meScore").html(player.score);
      $("#meMoveList").prepend(moveString);
    } else {
      $("#opponentScore").html(player.score);
      $("#opponentMoveList").prepend(moveString);
    }
    showNotice(moveScore, newWords, player);
    if (swapCoordinates) {
      swapTiles(swapCoordinates);
    }
    if (player.num !== myNum) {
      return startTurn(player, false);
    }
  };

  $(document).ready(function() {
    var oname, players, pname, urlVars;
    $('#grid li').live('click', tileClick);
    urlVars = getUrlVars();
    pname = Url.decode(urlVars["player"]);
    oname = Url.decode(urlVars["opponent"]);
    players = {
      p1: pname,
      p2: oname
    };
    socket = io.connect();
    // Set up event listeners for modern Socket.IO
    socket.on('welcome', handleWelcome);
    socket.on('moveResult', handleMoveResult);
    socket.on('opponentQuit', handleOpponentQuit);
    socket.on('timeIsUp', handleTimeIsUp);
    socket.on('yourTurnNow', handleYourTurnNow);
    socket.on('tick', handleTick);
    socket.on('gameOver', handleGameOver);
    socket.emit("newGame", `${JSON.stringify(players)}`);
    return socket.on('connect', function() {
      return showMessage('waitForConnection');
    });
  });

}).call(this);
